import { CombatAssetKeys, type CombatAssetKey } from "./combat-asset-keys";

export type CombatAssetBatch = "batch-01-ui-readability" | "batch-02-combat-identity" | "batch-03-card-art" | "batch-04-vfx";

export type CombatAssetDefinition = {
  readonly key: CombatAssetKey;
  readonly path: string;
  readonly batch: CombatAssetBatch;
  readonly requiredForBatch: boolean;
};

const batch01Asset = (key: CombatAssetKey, path: string): CombatAssetDefinition => ({
  key,
  path,
  batch: "batch-01-ui-readability",
  requiredForBatch: true
});

export const BATCH_01_COMBAT_ASSET_DEFINITIONS = [
  batch01Asset(CombatAssetKeys.cardFrames.normal, "assets/combat/cards/frames/combat_card_frame_normal.png"),
  batch01Asset(CombatAssetKeys.cardFrames.petCommand, "assets/combat/cards/frames/combat_card_frame_pet_command.png"),
  batch01Asset(CombatAssetKeys.cardFrames.petSupport, "assets/combat/cards/frames/combat_card_frame_pet_support.png"),
  batch01Asset(CombatAssetKeys.cardFrames.keeperSignal, "assets/combat/cards/frames/combat_card_frame_keeper_signal.png"),
  batch01Asset(CombatAssetKeys.cardFrames.futurePower, "assets/combat/cards/frames/combat_card_frame_future_power.png"),
  batch01Asset(CombatAssetKeys.cardFrames.temporary, "assets/combat/cards/frames/combat_card_frame_temporary.png"),
  batch01Asset(CombatAssetKeys.cardFrames.hoverOverlay, "assets/combat/cards/frames/combat_card_frame_hover_overlay.png"),
  batch01Asset(CombatAssetKeys.cardFrames.selectedOverlay, "assets/combat/cards/frames/combat_card_frame_selected_overlay.png"),
  batch01Asset(CombatAssetKeys.cardFrames.unplayableOverlay, "assets/combat/cards/frames/combat_card_frame_unplayable_overlay.png"),
  batch01Asset(CombatAssetKeys.cardFrames.artWindowPlaceholder, "assets/combat/cards/frames/combat_card_art_window_placeholder.png"),
  batch01Asset(CombatAssetKeys.cardRarityGems.starter, "assets/combat/cards/rarity/combat_card_rarity_starter.png"),
  batch01Asset(CombatAssetKeys.cardRarityGems.common, "assets/combat/cards/rarity/combat_card_rarity_common.png"),
  batch01Asset(CombatAssetKeys.cardRarityGems.uncommon, "assets/combat/cards/rarity/combat_card_rarity_uncommon.png"),
  batch01Asset(CombatAssetKeys.cardRarityGems.rare, "assets/combat/cards/rarity/combat_card_rarity_rare.png"),
  batch01Asset(CombatAssetKeys.cardRarityGems.special, "assets/combat/cards/rarity/combat_card_rarity_special.png"),
  batch01Asset(CombatAssetKeys.cardRarityGems.unique, "assets/combat/cards/rarity/combat_card_rarity_unique.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.universalPlayer, "assets/combat/cards/source_badges/combat_card_source_universal_player.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.classBound, "assets/combat/cards/source_badges/combat_card_source_class_bound.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.petBound, "assets/combat/cards/source_badges/combat_card_source_pet_bound.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.petSupport, "assets/combat/cards/source_badges/combat_card_source_pet_support.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.encounterReward, "assets/combat/cards/source_badges/combat_card_source_encounter_reward.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.eventOnly, "assets/combat/cards/source_badges/combat_card_source_event_only.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.temporary, "assets/combat/cards/source_badges/combat_card_source_temporary.png"),
  batch01Asset(CombatAssetKeys.cardSourceBadges.legacy, "assets/combat/cards/source_badges/combat_card_source_legacy.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.keeperAttack, "assets/combat/cards/family_badges/combat_card_family_keeper_attack.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.keeperSkill, "assets/combat/cards/family_badges/combat_card_family_keeper_skill.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.keeperSignal, "assets/combat/cards/family_badges/combat_card_family_keeper_signal.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.petCommand, "assets/combat/cards/family_badges/combat_card_family_pet_command.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.petSupport, "assets/combat/cards/family_badges/combat_card_family_pet_support.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.power, "assets/combat/cards/family_badges/combat_card_family_power.png"),
  batch01Asset(CombatAssetKeys.cardFamilyBadges.temporary, "assets/combat/cards/family_badges/combat_card_family_temporary.png"),
  batch01Asset(CombatAssetKeys.intentTokens.frame, "assets/combat/icons/intent/combat_intent_token_frame.png"),
  batch01Asset(CombatAssetKeys.icons.intentUnknown, "assets/combat/icons/intent/combat_icon_intent_unknown.png"),
  batch01Asset(CombatAssetKeys.icons.intentAttack, "assets/combat/icons/intent/combat_icon_intent_attack.png"),
  batch01Asset(CombatAssetKeys.icons.intentDefend, "assets/combat/icons/intent/combat_icon_intent_defend.png"),
  batch01Asset(CombatAssetKeys.icons.intentBuff, "assets/combat/icons/intent/combat_icon_intent_buff.png"),
  batch01Asset(CombatAssetKeys.icons.intentDebuff, "assets/combat/icons/intent/combat_icon_intent_debuff.png"),
  batch01Asset(CombatAssetKeys.icons.intentSpecial, "assets/combat/icons/intent/combat_icon_intent_special.png"),
  batch01Asset(CombatAssetKeys.icons.intentCharging, "assets/combat/icons/intent/combat_icon_intent_charging.png"),
  batch01Asset(CombatAssetKeys.icons.intentObscured, "assets/combat/icons/intent/combat_icon_intent_obscured.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.scoped, "assets/combat/icons/intent/combat_intent_marker_scoped.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.locked, "assets/combat/icons/intent/combat_intent_marker_locked.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.adaptive, "assets/combat/icons/intent/combat_intent_marker_adaptive.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.changedPulse, "assets/combat/icons/intent/combat_intent_marker_changed_pulse.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.multiHit, "assets/combat/icons/intent/combat_intent_marker_multi_hit.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.roughLow, "assets/combat/icons/intent/combat_intent_marker_rough_low.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.roughMedium, "assets/combat/icons/intent/combat_intent_marker_rough_medium.png"),
  batch01Asset(CombatAssetKeys.intentMarkers.roughHigh, "assets/combat/icons/intent/combat_intent_marker_rough_high.png"),
  batch01Asset(CombatAssetKeys.icons.statusBurn, "assets/combat/icons/status/combat_icon_status_burn.png"),
  batch01Asset(CombatAssetKeys.icons.statusBlock, "assets/combat/icons/status/combat_icon_status_block.png"),
  batch01Asset(CombatAssetKeys.icons.statusGuard, "assets/combat/icons/status/combat_icon_status_guard.png"),
  batch01Asset(CombatAssetKeys.icons.statusEmpowered, "assets/combat/icons/status/combat_icon_status_empowered.png"),
  batch01Asset(CombatAssetKeys.icons.statusMarked, "assets/combat/icons/status/combat_icon_status_marked.png"),
  batch01Asset(CombatAssetKeys.icons.statusReady, "assets/combat/icons/status/combat_icon_status_ready.png"),
  batch01Asset(CombatAssetKeys.icons.statusCommanded, "assets/combat/icons/status/combat_icon_status_commanded.png"),
  batch01Asset(CombatAssetKeys.icons.statusObscured, "assets/combat/icons/status/combat_icon_status_obscured.png"),
  batch01Asset(CombatAssetKeys.icons.statusScoped, "assets/combat/icons/status/combat_icon_status_scoped.png"),
  batch01Asset(CombatAssetKeys.icons.statusRevealed, "assets/combat/icons/status/combat_icon_status_revealed.png"),
  batch01Asset(CombatAssetKeys.icons.statusBound, "assets/combat/icons/status/combat_icon_status_bound.png"),
  batch01Asset(CombatAssetKeys.icons.statusOverflow, "assets/combat/icons/status/combat_icon_status_overflow.png"),
  batch01Asset(CombatAssetKeys.icons.statusFallback, "assets/combat/icons/status/combat_icon_status_fallback.png"),
  batch01Asset(CombatAssetKeys.icons.tagPetCommand, "assets/combat/icons/tags/combat_icon_tag_pet_command.png"),
  batch01Asset(CombatAssetKeys.icons.tagFox, "assets/combat/icons/tags/combat_icon_tag_fox.png"),
  batch01Asset(CombatAssetKeys.icons.tagBurn, "assets/combat/icons/tags/combat_icon_tag_burn.png"),
  batch01Asset(CombatAssetKeys.icons.tagGuard, "assets/combat/icons/tags/combat_icon_tag_guard.png"),
  batch01Asset(CombatAssetKeys.icons.tagBlock, "assets/combat/icons/tags/combat_icon_tag_block.png"),
  batch01Asset(CombatAssetKeys.icons.tagDraw, "assets/combat/icons/tags/combat_icon_tag_draw.png"),
  batch01Asset(CombatAssetKeys.icons.tagMark, "assets/combat/icons/tags/combat_icon_tag_mark.png"),
  batch01Asset(CombatAssetKeys.icons.tagAttack, "assets/combat/icons/tags/combat_icon_tag_attack.png"),
  batch01Asset(CombatAssetKeys.icons.tagSetup, "assets/combat/icons/tags/combat_icon_tag_setup.png"),
  batch01Asset(CombatAssetKeys.icons.tagCombo, "assets/combat/icons/tags/combat_icon_tag_combo.png"),
  batch01Asset(CombatAssetKeys.icons.tagKeeper, "assets/combat/icons/tags/combat_icon_tag_keeper.png"),
  batch01Asset(CombatAssetKeys.icons.tagSignal, "assets/combat/icons/tags/combat_icon_tag_signal.png"),
  batch01Asset(CombatAssetKeys.icons.tagScout, "assets/combat/icons/tags/combat_icon_tag_scout.png"),
  batch01Asset(CombatAssetKeys.icons.tagFetch, "assets/combat/icons/tags/combat_icon_tag_fetch.png"),
  batch01Asset(CombatAssetKeys.icons.tagReveal, "assets/combat/icons/tags/combat_icon_tag_reveal.png"),
  batch01Asset(CombatAssetKeys.icons.tagScope, "assets/combat/icons/tags/combat_icon_tag_scope.png"),
  batch01Asset(CombatAssetKeys.icons.tagObscure, "assets/combat/icons/tags/combat_icon_tag_obscure.png"),
  batch01Asset(CombatAssetKeys.icons.tagRare, "assets/combat/icons/tags/combat_icon_tag_rare.png"),
  batch01Asset(CombatAssetKeys.icons.tagFallback, "assets/combat/icons/tags/combat_icon_tag_fallback.png"),
  batch01Asset(CombatAssetKeys.uiPanels.bottomHudPlate, "assets/combat/ui/hud/combat_ui_bottom_hud_plate.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerHudFrame, "assets/combat/ui/hud/combat_ui_player_hud_frame.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerPortraitFrame, "assets/combat/ui/hud/combat_ui_player_portrait_frame.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerHpBarTrack, "assets/combat/ui/hud/combat_ui_player_hp_bar_track.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerHpBarFillMask, "assets/combat/ui/hud/combat_ui_player_hp_bar_fill_mask.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerBlockBadge, "assets/combat/ui/hud/combat_ui_player_block_badge.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerStatusTray, "assets/combat/ui/hud/combat_ui_player_status_tray.png"),
  batch01Asset(CombatAssetKeys.uiPanels.playerHoverFrame, "assets/combat/ui/hud/combat_ui_player_hover_frame.png"),
  batch01Asset(CombatAssetKeys.uiPanels.tooltipPanel, "assets/combat/ui/panels/combat_ui_tooltip_panel.png"),
  batch01Asset(CombatAssetKeys.uiPanels.detailPanel, "assets/combat/ui/panels/combat_ui_detail_panel.png"),
  batch01Asset(CombatAssetKeys.uiPanels.cardDetailSidebar, "assets/combat/ui/panels/combat_ui_card_detail_sidebar.png"),
  batch01Asset(CombatAssetKeys.uiPanels.cardDetailKeywordRow, "assets/combat/ui/panels/combat_ui_card_detail_keyword_row.png"),
  batch01Asset(CombatAssetKeys.uiPanels.cardDetailTagTray, "assets/combat/ui/panels/combat_ui_card_detail_tag_tray.png"),
  batch01Asset(CombatAssetKeys.uiPanels.detailCloseButton, "assets/combat/ui/panels/combat_ui_detail_close_button.png"),
  batch01Asset(CombatAssetKeys.uiPanels.clickBlockerTint, "assets/combat/ui/panels/combat_ui_click_blocker_tint.png"),
  batch01Asset(CombatAssetKeys.uiPanels.pausePanel, "assets/combat/ui/panels/combat_ui_pause_panel.png"),
  batch01Asset(CombatAssetKeys.uiPanels.eventLogPanel, "assets/combat/ui/panels/combat_ui_event_log_panel.png"),
  batch01Asset(CombatAssetKeys.controls.energyOrb, "assets/combat/ui/hud/combat_control_energy_orb.png"),
  batch01Asset(CombatAssetKeys.controls.drawPile, "assets/combat/ui/hud/combat_control_draw_pile.png"),
  batch01Asset(CombatAssetKeys.controls.discardPile, "assets/combat/ui/hud/combat_control_discard_pile.png"),
  batch01Asset(CombatAssetKeys.controls.endTurnButton, "assets/combat/ui/hud/combat_control_end_turn_button.png"),
  batch01Asset(CombatAssetKeys.controls.menuButton, "assets/combat/ui/hud/combat_control_menu_button.png"),
  batch01Asset(CombatAssetKeys.slots.petRing, "assets/combat/ui/slots/combat_slot_pet_ring.png"),
  batch01Asset(CombatAssetKeys.slots.petCommandGlow, "assets/combat/ui/slots/combat_slot_pet_command_glow.png"),
  batch01Asset(CombatAssetKeys.slots.emberChargePip, "assets/combat/ui/slots/combat_slot_ember_charge_pip.png"),
  batch01Asset(CombatAssetKeys.slots.petStatusTray, "assets/combat/ui/slots/combat_slot_pet_status_tray.png"),
  batch01Asset(CombatAssetKeys.slots.inactivePetSlot, "assets/combat/ui/slots/combat_slot_inactive_pet_slot.png"),
  batch01Asset(CombatAssetKeys.slots.enemyTargetRing, "assets/combat/ui/slots/combat_slot_enemy_target_ring.png"),
  batch01Asset(CombatAssetKeys.slots.enemyHpBarTrack, "assets/combat/ui/slots/combat_slot_enemy_hp_bar_track.png"),
  batch01Asset(CombatAssetKeys.slots.enemyHpBarFillMask, "assets/combat/ui/slots/combat_slot_enemy_hp_bar_fill_mask.png"),
  batch01Asset(CombatAssetKeys.slots.enemyBlockBadge, "assets/combat/ui/slots/combat_slot_enemy_block_badge.png"),
  batch01Asset(CombatAssetKeys.slots.enemyStatusTray, "assets/combat/ui/slots/combat_slot_enemy_status_tray.png"),
] as const satisfies readonly CombatAssetDefinition[];

export const COMBAT_ASSET_DEFINITIONS = [
  ...BATCH_01_COMBAT_ASSET_DEFINITIONS
] as const satisfies readonly CombatAssetDefinition[];

export const getCombatAssetDefinition = (key: CombatAssetKey): CombatAssetDefinition | undefined =>
  COMBAT_ASSET_DEFINITIONS.find((definition) => definition.key === key);
