import { describe, expect, it } from "vitest";
import {
  CombatAssetKeys,
  getCombatAssetKeys,
  getCombatAssetKeysForGroup
} from "../../src/game-phaser/assets/combat-asset-keys";

const expectedCombatAssetKeys = [
  CombatAssetKeys.backgrounds.ashwoodCombat,
  CombatAssetKeys.backgrounds.ashwoodSkyRuins,
  CombatAssetKeys.backgrounds.ashwoodMidTrees,
  CombatAssetKeys.backgrounds.ashwoodGroundPlane,
  CombatAssetKeys.backgrounds.ashwoodForegroundAsh,
  CombatAssetKeys.backgrounds.neutralBoardFallback,
  CombatAssetKeys.uiPanels.bottomHudPlate,
  CombatAssetKeys.uiPanels.playerHudFrame,
  CombatAssetKeys.uiPanels.playerPortraitFrame,
  CombatAssetKeys.uiPanels.playerHpBarTrack,
  CombatAssetKeys.uiPanels.playerHpBarFillMask,
  CombatAssetKeys.uiPanels.playerBlockBadge,
  CombatAssetKeys.uiPanels.playerStatusTray,
  CombatAssetKeys.uiPanels.playerHoverFrame,
  CombatAssetKeys.uiPanels.tooltipPanel,
  CombatAssetKeys.uiPanels.detailPanel,
  CombatAssetKeys.uiPanels.cardDetailSidebar,
  CombatAssetKeys.uiPanels.cardDetailKeywordRow,
  CombatAssetKeys.uiPanels.cardDetailTagTray,
  CombatAssetKeys.uiPanels.detailCloseButton,
  CombatAssetKeys.uiPanels.clickBlockerTint,
  CombatAssetKeys.uiPanels.pausePanel,
  CombatAssetKeys.uiPanels.eventLogPanel,
  CombatAssetKeys.controls.energyOrb,
  CombatAssetKeys.controls.drawPile,
  CombatAssetKeys.controls.discardPile,
  CombatAssetKeys.controls.endTurnButton,
  CombatAssetKeys.controls.menuButton,
  CombatAssetKeys.cardFrames.normal,
  CombatAssetKeys.cardFrames.petCommand,
  CombatAssetKeys.cardFrames.petSupport,
  CombatAssetKeys.cardFrames.keeperSignal,
  CombatAssetKeys.cardFrames.futurePower,
  CombatAssetKeys.cardFrames.temporary,
  CombatAssetKeys.cardFrames.hoverOverlay,
  CombatAssetKeys.cardFrames.selectedOverlay,
  CombatAssetKeys.cardFrames.unplayableOverlay,
  CombatAssetKeys.cardFrames.artWindowPlaceholder,
  CombatAssetKeys.cardRarityGems.starter,
  CombatAssetKeys.cardRarityGems.common,
  CombatAssetKeys.cardRarityGems.uncommon,
  CombatAssetKeys.cardRarityGems.rare,
  CombatAssetKeys.cardRarityGems.special,
  CombatAssetKeys.cardRarityGems.unique,
  CombatAssetKeys.cardSourceBadges.universalPlayer,
  CombatAssetKeys.cardSourceBadges.classBound,
  CombatAssetKeys.cardSourceBadges.petBound,
  CombatAssetKeys.cardSourceBadges.petSupport,
  CombatAssetKeys.cardSourceBadges.encounterReward,
  CombatAssetKeys.cardSourceBadges.eventOnly,
  CombatAssetKeys.cardSourceBadges.temporary,
  CombatAssetKeys.cardSourceBadges.legacy,
  CombatAssetKeys.cardFamilyBadges.keeperAttack,
  CombatAssetKeys.cardFamilyBadges.keeperSkill,
  CombatAssetKeys.cardFamilyBadges.keeperSignal,
  CombatAssetKeys.cardFamilyBadges.power,
  CombatAssetKeys.cardFamilyBadges.petCommand,
  CombatAssetKeys.cardFamilyBadges.petSupport,
  CombatAssetKeys.cardFamilyBadges.temporary,
  CombatAssetKeys.cardArt.keepersTap,
  CombatAssetKeys.cardArt.fieldBrace,
  CombatAssetKeys.cardArt.readTheAsh,
  CombatAssetKeys.cardArt.foxBite,
  CombatAssetKeys.cardArt.tailguard,
  CombatAssetKeys.cardArt.kindleMark,
  CombatAssetKeys.cardArt.fetchSignal,
  CombatAssetKeys.icons.intentAttack,
  CombatAssetKeys.icons.intentDefend,
  CombatAssetKeys.icons.intentBuff,
  CombatAssetKeys.icons.intentDebuff,
  CombatAssetKeys.icons.intentSpecial,
  CombatAssetKeys.icons.intentUnknown,
  CombatAssetKeys.icons.intentCharging,
  CombatAssetKeys.icons.intentObscured,
  CombatAssetKeys.icons.statusBurn,
  CombatAssetKeys.icons.statusBlock,
  CombatAssetKeys.icons.statusGuard,
  CombatAssetKeys.icons.statusEmpowered,
  CombatAssetKeys.icons.statusMarked,
  CombatAssetKeys.icons.statusReady,
  CombatAssetKeys.icons.statusCommanded,
  CombatAssetKeys.icons.statusObscured,
  CombatAssetKeys.icons.statusScoped,
  CombatAssetKeys.icons.statusRevealed,
  CombatAssetKeys.icons.statusBound,
  CombatAssetKeys.icons.statusOverflow,
  CombatAssetKeys.icons.statusFallback,
  CombatAssetKeys.icons.tagPetCommand,
  CombatAssetKeys.icons.tagFox,
  CombatAssetKeys.icons.tagBurn,
  CombatAssetKeys.icons.tagGuard,
  CombatAssetKeys.icons.tagBlock,
  CombatAssetKeys.icons.tagDraw,
  CombatAssetKeys.icons.tagMark,
  CombatAssetKeys.icons.tagAttack,
  CombatAssetKeys.icons.tagSetup,
  CombatAssetKeys.icons.tagCombo,
  CombatAssetKeys.icons.tagKeeper,
  CombatAssetKeys.icons.tagSignal,
  CombatAssetKeys.icons.tagScout,
  CombatAssetKeys.icons.tagFetch,
  CombatAssetKeys.icons.tagReveal,
  CombatAssetKeys.icons.tagScope,
  CombatAssetKeys.icons.tagObscure,
  CombatAssetKeys.icons.tagRare,
  CombatAssetKeys.icons.tagFallback,
  CombatAssetKeys.intentTokens.frame,
  CombatAssetKeys.intentMarkers.scoped,
  CombatAssetKeys.intentMarkers.locked,
  CombatAssetKeys.intentMarkers.adaptive,
  CombatAssetKeys.intentMarkers.changedPulse,
  CombatAssetKeys.intentMarkers.multiHit,
  CombatAssetKeys.intentMarkers.roughLow,
  CombatAssetKeys.intentMarkers.roughMedium,
  CombatAssetKeys.intentMarkers.roughHigh,
  CombatAssetKeys.combatants.keeperIdle,
  CombatAssetKeys.combatants.keeperCommand,
  CombatAssetKeys.combatants.keeperAttack,
  CombatAssetKeys.combatants.keeperHurt,
  CombatAssetKeys.combatants.keeperHurtGuarded,
  CombatAssetKeys.combatants.emberFoxIdle,
  CombatAssetKeys.combatants.emberFoxCommandReady,
  CombatAssetKeys.combatants.emberFoxBite,
  CombatAssetKeys.combatants.emberFoxTailguard,
  CombatAssetKeys.combatants.emberFoxBurnApply,
  CombatAssetKeys.combatants.emberFoxCalm,
  CombatAssetKeys.combatants.enemyGenericIdle,
  CombatAssetKeys.combatants.enemyAshSlimeIdle,
  CombatAssetKeys.combatants.enemyCinderMiteIdle,
  CombatAssetKeys.combatants.enemySootCrowIdle,
  CombatAssetKeys.combatants.enemyRootHuskIdle,
  CombatAssetKeys.combatants.enemyCharredStagIdle,
  CombatAssetKeys.combatants.enemyCinderScribeIdle,
  CombatAssetKeys.combatants.enemyEmberrootWardenIdle,
  CombatAssetKeys.slots.petRing,
  CombatAssetKeys.slots.petCommandGlow,
  CombatAssetKeys.slots.emberChargePip,
  CombatAssetKeys.slots.petStatusTray,
  CombatAssetKeys.slots.inactivePetSlot,
  CombatAssetKeys.slots.enemyTargetRing,
  CombatAssetKeys.slots.enemyHpBarTrack,
  CombatAssetKeys.slots.enemyHpBarFillMask,
  CombatAssetKeys.slots.enemyBlockBadge,
  CombatAssetKeys.slots.enemyStatusTray,
  CombatAssetKeys.vfx.commandThread,
  CombatAssetKeys.vfx.commandMarker,
  CombatAssetKeys.vfx.endpointRuneFlash,
  CombatAssetKeys.vfx.targetRingPulse,
  CombatAssetKeys.vfx.cardPlayFlash,
  CombatAssetKeys.vfx.energySpendPulse,
  CombatAssetKeys.vfx.impactBurst,
  CombatAssetKeys.vfx.burnApplyPop,
  CombatAssetKeys.vfx.burnTick,
  CombatAssetKeys.vfx.shieldArc,
  CombatAssetKeys.vfx.statusPop,
  CombatAssetKeys.vfx.intentChangedPulse,
  CombatAssetKeys.vfx.intentResolvePulse,
  CombatAssetKeys.vfx.defeatBurst
] as const;

describe("combat asset keys", () => {
  it("groups stable combat replacement points", () => {
    expect(CombatAssetKeys).toMatchObject({
      backgrounds: expect.any(Object),
      uiPanels: expect.any(Object),
      cardFrames: expect.any(Object),
      cardRarityGems: expect.any(Object),
      cardSourceBadges: expect.any(Object),
      cardFamilyBadges: expect.any(Object),
      cardArt: expect.any(Object),
      icons: expect.any(Object),
      intentTokens: expect.any(Object),
      intentMarkers: expect.any(Object),
      combatants: expect.any(Object),
      slots: expect.any(Object),
      vfx: expect.any(Object)
    });
    expect(getCombatAssetKeysForGroup("cardFrames")).toContain(CombatAssetKeys.cardFrames.petCommand);
    expect(getCombatAssetKeysForGroup("vfx")).toContain(CombatAssetKeys.vfx.commandThread);
  });

  it("matches the manifest-backed runtime key contract exactly", () => {
    expect([...getCombatAssetKeys()].sort()).toEqual([...expectedCombatAssetKeys].sort());
  });

  it("defines 4K-ready parallax, official enemy, and card visual engine replacement points", () => {
    expect(getCombatAssetKeys()).toEqual(expect.arrayContaining([
      CombatAssetKeys.backgrounds.ashwoodSkyRuins,
      CombatAssetKeys.backgrounds.ashwoodMidTrees,
      CombatAssetKeys.backgrounds.ashwoodGroundPlane,
      CombatAssetKeys.backgrounds.ashwoodForegroundAsh,
      CombatAssetKeys.combatants.keeperIdle,
      CombatAssetKeys.combatants.keeperCommand,
      CombatAssetKeys.combatants.keeperAttack,
      CombatAssetKeys.combatants.keeperHurtGuarded,
      CombatAssetKeys.combatants.emberFoxIdle,
      CombatAssetKeys.combatants.emberFoxCommandReady,
      CombatAssetKeys.combatants.emberFoxBite,
      CombatAssetKeys.combatants.emberFoxTailguard,
      CombatAssetKeys.combatants.emberFoxBurnApply,
      CombatAssetKeys.combatants.emberFoxCalm,
      CombatAssetKeys.combatants.enemyAshSlimeIdle,
      CombatAssetKeys.combatants.enemyCinderMiteIdle,
      CombatAssetKeys.combatants.enemySootCrowIdle,
      CombatAssetKeys.combatants.enemyRootHuskIdle,
      CombatAssetKeys.combatants.enemyCharredStagIdle,
      CombatAssetKeys.combatants.enemyCinderScribeIdle,
      CombatAssetKeys.combatants.enemyEmberrootWardenIdle,
      CombatAssetKeys.cardRarityGems.starter,
      CombatAssetKeys.cardRarityGems.rare,
      CombatAssetKeys.cardSourceBadges.classBound,
      CombatAssetKeys.cardSourceBadges.petBound,
      CombatAssetKeys.cardFamilyBadges.keeperSignal,
      CombatAssetKeys.cardFamilyBadges.petCommand,
      CombatAssetKeys.cardFamilyBadges.temporary,
      CombatAssetKeys.cardFrames.keeperSignal,
      CombatAssetKeys.cardFrames.temporary,
      CombatAssetKeys.cardArt.foxBite,
      CombatAssetKeys.cardArt.fetchSignal
    ]));
  });

  it("matches manifest names for sequence-aware intent markers and status/tag icons", () => {
    expect(getCombatAssetKeys()).toEqual(expect.arrayContaining([
      CombatAssetKeys.intentTokens.frame,
      CombatAssetKeys.intentMarkers.scoped,
      CombatAssetKeys.intentMarkers.locked,
      CombatAssetKeys.intentMarkers.adaptive,
      CombatAssetKeys.intentMarkers.changedPulse,
      CombatAssetKeys.intentMarkers.multiHit,
      CombatAssetKeys.intentMarkers.roughLow,
      CombatAssetKeys.intentMarkers.roughMedium,
      CombatAssetKeys.intentMarkers.roughHigh,
      CombatAssetKeys.icons.statusCommanded,
      CombatAssetKeys.icons.statusObscured,
      CombatAssetKeys.icons.statusScoped,
      CombatAssetKeys.icons.statusRevealed,
      CombatAssetKeys.icons.statusBound,
      CombatAssetKeys.icons.tagKeeper,
      CombatAssetKeys.icons.tagScout,
      CombatAssetKeys.icons.tagReveal,
      CombatAssetKeys.icons.tagScope,
      CombatAssetKeys.icons.tagObscure,
      CombatAssetKeys.icons.tagRare,
      CombatAssetKeys.icons.tagFallback
    ]));
  });

  it("defines manifest-required HUD, pet, enemy, and overlay replacement points", () => {
    expect(getCombatAssetKeys()).toEqual(expect.arrayContaining([
      CombatAssetKeys.uiPanels.playerPortraitFrame,
      CombatAssetKeys.uiPanels.playerHpBarTrack,
      CombatAssetKeys.uiPanels.playerHpBarFillMask,
      CombatAssetKeys.uiPanels.playerBlockBadge,
      CombatAssetKeys.uiPanels.playerStatusTray,
      CombatAssetKeys.uiPanels.playerHoverFrame,
      CombatAssetKeys.uiPanels.cardDetailSidebar,
      CombatAssetKeys.uiPanels.cardDetailKeywordRow,
      CombatAssetKeys.uiPanels.cardDetailTagTray,
      CombatAssetKeys.uiPanels.detailCloseButton,
      CombatAssetKeys.uiPanels.clickBlockerTint,
      CombatAssetKeys.slots.petRing,
      CombatAssetKeys.slots.petCommandGlow,
      CombatAssetKeys.slots.emberChargePip,
      CombatAssetKeys.slots.petStatusTray,
      CombatAssetKeys.slots.inactivePetSlot,
      CombatAssetKeys.slots.enemyTargetRing,
      CombatAssetKeys.slots.enemyHpBarTrack,
      CombatAssetKeys.slots.enemyHpBarFillMask,
      CombatAssetKeys.slots.enemyBlockBadge,
      CombatAssetKeys.slots.enemyStatusTray,
      CombatAssetKeys.controls.energyOrb,
      CombatAssetKeys.controls.drawPile,
      CombatAssetKeys.controls.discardPile,
      CombatAssetKeys.controls.endTurnButton
    ]));
  });

  it("keeps Phase 1 exclusions out of the runtime key contract", () => {
    const keys = getCombatAssetKeys().join("\n");

    expect(keys).not.toMatch(/pet.*hp|hp.*pet/i);
    expect(keys).not.toMatch(/enemy.*battlefield.*card|battlefield.*enemy.*card/i);
    expect(keys).not.toMatch(/trainingSlime/i);
    expect(keys).not.toMatch(/hitbox/i);
    expect(keys).not.toMatch(/pet.*target/i);
  });
});
