type Brand<K, T extends string> = K & { readonly __brand: T };

export type CardId = Brand<string, "CardId">;
export type CardInstanceId = Brand<string, "CardInstanceId">;
export type PetDefinitionId = Brand<string, "PetDefinitionId">;
export type PetInstanceId = Brand<string, "PetInstanceId">;
export type PlayerClassId = Brand<string, "PlayerClassId">;
export type MonsterId = Brand<string, "MonsterId">;
export type UpgradeId = Brand<string, "UpgradeId">;
export type StoryEventId = Brand<string, "StoryEventId">;
export type StoryFlagId = Brand<string, "StoryFlagId">;
export type StatusId = Brand<string, "StatusId">;
export type RunId = Brand<string, "RunId">;
export type CombatantId = Brand<string, "CombatantId">;
export type MonsterIntentId = Brand<string, "MonsterIntentId">;
export type RewardOfferId = Brand<string, "RewardOfferId">;
export type RewardOptionId = Brand<string, "RewardOptionId">;
export type RelicId = Brand<string, "RelicId">;
export type PetMemoryId = Brand<string, "PetMemoryId">;
export type EvolutionNodeId = Brand<string, "EvolutionNodeId">;
export type PetModifierId = Brand<string, "PetModifierId">;
export type RunMapId = Brand<string, "RunMapId">;
export type RunNodeId = Brand<string, "RunNodeId">;
export type EncounterId = Brand<string, "EncounterId">;
export type RunTemplateId = Brand<string, "RunTemplateId">;

export const cardId = (value: string): CardId => value as CardId;
export const cardInstanceId = (value: string): CardInstanceId => value as CardInstanceId;
export const petDefinitionId = (value: string): PetDefinitionId => value as PetDefinitionId;
export const petInstanceId = (value: string): PetInstanceId => value as PetInstanceId;
export const playerClassId = (value: string): PlayerClassId => value as PlayerClassId;
export const monsterId = (value: string): MonsterId => value as MonsterId;
export const upgradeId = (value: string): UpgradeId => value as UpgradeId;
export const storyEventId = (value: string): StoryEventId => value as StoryEventId;
export const storyFlagId = (value: string): StoryFlagId => value as StoryFlagId;
export const statusId = (value: string): StatusId => value as StatusId;
export const runId = (value: string): RunId => value as RunId;
export const combatantId = (value: string): CombatantId => value as CombatantId;
export const monsterIntentId = (value: string): MonsterIntentId => value as MonsterIntentId;
export const rewardOfferId = (value: string): RewardOfferId => value as RewardOfferId;
export const rewardOptionId = (value: string): RewardOptionId => value as RewardOptionId;
export const relicId = (value: string): RelicId => value as RelicId;
export const petMemoryId = (value: string): PetMemoryId => value as PetMemoryId;
export const evolutionNodeId = (value: string): EvolutionNodeId => value as EvolutionNodeId;
export const petModifierId = (value: string): PetModifierId => value as PetModifierId;
export const runMapId = (value: string): RunMapId => value as RunMapId;
export const runNodeId = (value: string): RunNodeId => value as RunNodeId;
export const encounterId = (value: string): EncounterId => value as EncounterId;
export const runTemplateId = (value: string): RunTemplateId => value as RunTemplateId;
